[build]
  base = "./"
  publish = "./dist/"
  command = "npm run build"
  environment = { NODE_VERSION = "18" }

[template.environment]
  NAME = "enter Name of the receiver"
  PIC = "enter web url of the receiver's image"
